spring.application.name=roomloop


#DB configuration
spring.datasource.url=jdbc:mysql://localhost:3306/roomloopdb
spring.datasource.username=root
spring.datasource.password=root


spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


server.servlet.context-path=/api

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false


spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
